### ISSUE TITLE
Uncaught TypeError: code.replace is not a function

### ISSUE THREAD

**Issue by acarril** [kylebarron/stata-exec#18]
Sometimes I randomly get this error. Will try to replicate the exact trigger conditions.

**Atom**: 1.23.2 x64
**Electron**: 1.6.15
**OS**: Ubuntu 16.04.3
**Thrown From**: [stata-exec](https://github.com/kylebarron/stata-exec) package 1.2.1

### Stack Trace

Uncaught TypeError: code.replace is not a function

```
At /home/alvaro/.atom/packages/stata-exec/lib/stata-exec.js:152

TypeError: code.replace is not a function
    at Object.removeComments (/packages/stata-exec/lib/stata-exec.js:152:17)
    at Object.sendCode (/packages/stata-exec/lib/stata-exec.js:164:17)
    at Object.sendPreviousCommand (/packages/stata-exec/lib/stata-exec.js:160:17)
    at HTMLElement.subscriptions.add.atom.commands.add (/packages/stata-exec/lib/stata-exec.js:82:54)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:388:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app/src/window-event-handler.js:108:40)
```

### Commands

```
     -0:40.4.0 core:move-right (input.hidden-input)
     -0:39.5.0 core:move-down (input.hidden-input)
 16x -0:39.2.0 core:move-left (input.hidden-input)
 13x -0:37.6.0 core:select-left (input.hidden-input)
 11x -0:33.6.0 core:move-right (input.hidden-input)
     -0:32.2.0 core:move-left (input.hidden-input)
  4x -0:31.9.0 core:select-right (input.hidden-input)
 12x -0:27.7.0 core:move-right (input.hidden-input)
     -0:23.5.0 core:move-left (input.hidden-input)
     -0:22.3.0 core:move-right (input.hidden-input)
  6x -0:21.2.0 core:move-left (input.hidden-input)
  5x -0:19.6.0 core:select-right (input.hidden-input)
     -0:17.5.0 core:move-right (input.hidden-input)
     -0:09.1.0 core:move-up (input.hidden-input)
     -0:08.5.0 core:move-down (input.hidden-input)
     -0:07.0 stata-exec:send-previous-command (input.hidden-input)
```

### Non-Core Packages

```
file-icons 2.1.15 
language-latex 1.1.1 
language-stata 1.3.0 
latex 0.49.0 
latextools 0.8.5 
project-manager 3.3.5 
stata-exec 1.2.1 
```

**Comment by kylebarron** [comment]
Do you still get this?

**Comment by acarril** [comment]
Not since your last update.

**Comment by kylebarron** [comment]
Ok just reopen the issue if you see it again
