### ISSUE TITLE
Unable to install Windows-build-tools

### ISSUE THREAD

**Issue by abarenbe** [kylebarron/stata-exec#44]
Going through the windows install steps, after installing Node.js 7.4 and running 

`npm install --global --production windows-build-tools`
From the Window Power Shell (ran as administrator) I get this error message:

> SyntaxError: Unexpected token function
>     at Object.exports.runInThisContext (vm.js:78:16)
>     at Module._compile (module.js:543:28)
>     at Object.Module._extensions..js (module.js:580:10)
>     at Module.load (module.js:488:32)
>     at tryModuleLoad (module.js:447:12)
>     at Function.Module._load (module.js:439:3)
>     at Module.require (module.js:498:17)
>     at require (internal/module.js:20:19)

Any help would be appreciated.

**Comment by kylebarron** [comment]
The issue is that the Node version was current for the version of Atom when I originally wrote the README. Since then, Atom has been updated and uses a newer version of Noe.

**Comment by kylebarron** [comment]
If someone would like to submit a PR with new instructions I'd take a look

**Comment by alvarocalderon** [comment]
Did anybody find a solution? Please share it :-)
