### ISSUE TITLE
Uncaught TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by rvaldezr** [kylebarron/stata-exec#45]
When I use ctrl+enter, it just pump up a new Stata window, but do nothing. It doesn't run any command.

I tried with a single: sysuse dir.

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Unknown Windows version
**Thrown From**: [stata-exec](https://github.com/kylebarron/stata-exec) package 1.8.6

### Stack Trace

Uncaught TypeError: Path must be a string. Received undefined

```
At path.js:28

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.join (path.js:501:7)
    at Object.runBatch (/packages/stata-exec/lib/main.js:155:25)
    at Object.run (/packages/stata-exec/lib/main.js:129:14)
    at HTMLElement.subscriptions.add.atom.commands.add (/packages/stata-exec/lib/main.js:80:42)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:350017)
    at KeymapManager.t.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:1212945)
    at KeymapManager.t.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:1209079)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:285196)
```

### Commands

```
     -5:44.5.0 core:save-as (input.hidden-input)
     -5:22.1.0 autocomplete-plus:confirm (input.hidden-input)
     -5:13.8.0 stata-exec:run (input.hidden-input)
     -5:01.1.0 core:move-left (input.hidden-input)
     -5:00.5.0 stata-exec:run (input.hidden-input)
     -1:29.3.0 stata-exec:run-batch (input.hidden-input)
     -1:26 stata-exec:run (input.hidden-input)
     -1:09.3.0 stata-exec:set-working-directory (input.hidden-input)
     -0:11.5.0 core:backspace (input.hidden-input)
     -0:11 stata-exec:run (input.hidden-input)
```

### Non-Core Packages

```
Hydrogen undefined 
language-stata 1.7.3 
stata-exec 1.8.6 
```

**Comment by kylebarron** [comment]
It's very hard to get this to work on Windows, so I don't officially support it and can't really give advice. I would strongly recommend to try [stata_kernel](https://kylebarron.github.io/stata_kernel/) which has a much easier installation process on Windows.

**Comment by znxkxx** [comment]
I also encountered this problem. and noticed that the error came from the following code (from main.js, line 155):
`var codepath = path.join(process.env.HOME, '.stata-exec_batch_code');`
It throw an error that Path must be a string because process.env.HOME is not defined on my PC.  this issue is solved once I manually defined environment variable HOME.  For defining this environment variable on Windows 10 paltform, you may do the followings: right click "This computer" --> "properties" --> Click Environment Variables, the create a new environment variable named **HOME**, for example, "C:\users\jack"

**Comment by znxkxx** [comment]
By the way. I install the latest version of Node js. and I run Atom on Win10 System
