### ISSUE TITLE
No output in Atom

### ISSUE THREAD

**Issue by Andrei-WongE** [kylebarron/stata-exec#46]
Thank you for the incredible package!

But, I have the following problem having been through all the install instructions on a Windows 10. I open my do file and try the following code:
```
sysuse auto, clear
regress price headroom trunk weight length
```
I get the following output in the console:
```
Uncaught Error: spawn C:\Stata15 ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```
I have no idea what went wrong...

**Comment by kylebarron** [comment]
It's really hard to get this to work on Windows, so I'm not supporting/giving advice for Windows anymore. [Stata_kernel](https://kylebarron.github.io/stata_kernel/) is much easier to get working on Windows.
